footer ready to PR
adrianponce89/kraken-web pull request #17
Opened 2023-03-31 18:00 UTC by germankern

Footer terminado y responsive. 

mobile: 
![image](https://user-images.githubusercontent.com/104010145/229195367-260ef13a-6cff-4590-bdd0-b9b7fe514fcc.png)

tablet:
![image](https://user-images.githubusercontent.com/104010145/229195477-16cf92a9-c8bc-4096-af5f-0d5966748590.png)

desktop:
![image](https://user-images.githubusercontent.com/104010145/229195597-bc9b3f90-2724-4158-a7b5-7e12c6ed73d7.png)

2023-03-31 19:33 UTC, adrianponce89 requested changes

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +    justify-content: space-around;
```
    justify-content: space-between;
```

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
```
$column-width-md: 17rem; //272px
$column-width-sm: 12.5rem; //200px
```

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +      width: 270px;
```
      width: $column-width-md;
```
Evita usar numeros sueltos (se les suele llamar "numeros magicos").
Los numeros que no son autodescriptivos (como `0` `1` `100%`) tienen que estar guardados en una variable que diga que significan

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +      width: 270px;
```
      width: $column-width-md;
```

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +@media screen and (max-width: $sizeTablet) {
En vez de `@media screen and (max-width: $sizeTablet) {` pone `@include for-tablet-only {`
Y agrega al archivo src/styles/theme.scss entre la linea 80-82:
```
@mixin for-tablet-only {
  @media (max-width: $sizeTabletSm) {
    // 768px
    @content;
  }
}
```

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +        width: 200px;
```
        width: $column-width-sm;
```

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +        width: 200px;
```
        width: $column-width-sm;
```

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +          font-weight: 600;
Reemplzalo por:
```
          @include font-sm(600);
```

Y en el archivo theme.csss reemplaza el mixin de font-sm por uno que reciba weight, (hacelo para el resto de mixines de fonts)
```
@mixin font-sm($weight: 400) {
  font-weight: $weight;
  font-style: normal;
  font-size: 14px;
  line-height: 19px;
  font-family: $main-font-family;
}
```

2023-03-31 19:33 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +          font-weight: 600;
@include font-sm(600);

2023-03-31 20:58 UTC, germankern commented
Buenisimo! Ahi hice los cambio que me pediste, el unico que me queda la duda es porque space betwenn y no arround? 

![image](https://user-images.githubusercontent.com/104010145/229228742-d3088613-a7d6-48cc-aa38-20699a0d3918.png)

deje el betwenn pero tube que agregarle padding left al container left y padding right al container right

2023-03-31 21:16 UTC, adrianponce89 requested changes

2023-03-31 21:16 UTC, adrianponce89 commented on src/components/Footer/index.scss
> +    max-height: $column-width-lg;
Acá se esta mezclando alto con ancho.
height es alto y width es ancho.
ademas este es el innerContainer, no es una columna (lo que son columnas son lo de adentro de este que es display: flex). Yo le pondria de nombre $footer-max-height, agregalo en la parte de arriba de este mismo archivo junto con $column-width-md y $column-width-sm. No lo agregues en el archivo de theme (porque es una constante exclusiva del footer, no de toda la app)

2023-03-31 21:16 UTC, adrianponce89 commented on src/styles/theme.scss
> +
Estos no van aca, irian en `src/components/Footer/index.scss` justo un espacio debajo del @import

2023-03-31 21:16 UTC, adrianponce89 commented on src/styles/theme.scss
> +}
Deja un espacio entre mixin y mixin, no cambia mucho pero es mas claro donde termina y comienza el otro a simple vista.
Esto es una opinion sobre un estilo de codigo, pero el estilo que haya se tiene que mantener en toda la app, si lo cambias aca, deberias cambiarlo en toda la app

2023-03-31 21:16 UTC, adrianponce89 commented on src/styles/theme.scss
> +    // 624px
No se porque cambiaste este, pero bien.
Si queres saber podes convertir px a rem y viceversa. por ejemplo con esta pagina: https://nekocalc.com/px-to-rem-converter

2023-04-04 13:31 UTC, adrianponce89 approved these changes

2023-04-04 13:32 UTC, merged