progress in hero section
adrianponce89/kraken-web pull request #19
Opened 2023-04-10 16:06 UTC by germankern

No estoy seguro como hacer esto o si tiene que quedar exacto como el figma. 

![image](https://user-images.githubusercontent.com/104010145/230941764-b6356448-6d50-4248-9665-79877c5f6d94.png)

Porejemplo el 60+, diverse y entensive lo habia puesto como imagenes... despues lo puse como texto con las misma propiedades y no se ven exactos.

![image](https://user-images.githubusercontent.com/104010145/230942196-667898a9-077f-457a-af5e-171366669076.png)
Y otra cosa, el pulpo que se ve como background image, tmb lo cambie muchas veces... pero me di cuenta que la imagen no es entera, hay 3, intenté acomodar esas 2 imagenes mas que serian como los tentaculos peor no pude o no se hacia responsive. Ese SVG deberia ser la imagen entera? O como haria eso?

2023-04-10 17:17 UTC, germankern commented
Ahí lo vi al SVG entero con los textos, quedó así. 

![image](https://user-images.githubusercontent.com/104010145/230954332-dca57f93-b7c0-477b-8746-45f5693814f8.png)

Lo único que creo que debería cambiarle el  margen en mobile por un $margin-lg 0px  para qeu no quede muy abajo, no? 
.textHeroSection {
      margin: $margin-xxl 0px;

2023-04-10 18:19 UTC, adrianponce89 commented on src/components/HeroSection/index.scss
> +  background-size: 100% 100%;
Si vos usas 100% 100% la imagen de background siempre va a tener el mismo tamaño que  .heroSection y eso va a ahacer que si heroSection es mas chico o mas largo la imagen se achate o se estire. La idea es que la imagen mantenga su proporcion siempre
background-size: 100vw 290vw;

2023-04-10 18:20 UTC, adrianponce89 commented on src/components/HeroSection/index.scss
> +  background-size: 100% 100%;
vw significa "viewport width", osea "el ancho de la vista"

2023-04-10 20:30 UTC, germankern commented on src/components/HeroSection/index.scss
> +  background-size: 100% 100%;
Ok, entiendo. Esa proporción la calculaste sabiendo que tiene casi el triple de alto que de ancho? 
Pensé que eso se acomodaba con aspect-ratio.

2023-04-10 20:31 UTC, germankern commented on src/components/HeroSection/index.scss
> +  background-size: 100% 100%;
![image](https://user-images.githubusercontent.com/104010145/230992501-850eed2d-8922-4055-b9e4-41d29b913930.png)

2023-04-11 16:25 UTC, adrianponce89 commented on src/components/HeroSection/index.scss
> +  background-size: 100% 100%;
Claro, la calcule sabiendo el tamaño de la imagen que usas de background. El aspect-ratio es para img, esto es un background-image por eso son diferentes

2023-04-11 16:29 UTC, adrianponce89 requested changes

2023-04-11 17:54 UTC, merged