Our services
adrianponce89/kraken-web pull request #22
Opened 2023-04-14 20:48 UTC by germankern

![image](https://user-images.githubusercontent.com/104010145/232151748-e5ec5496-816b-490f-8279-22e0117e213b.png)

Creo que me  falta ver porque no funciona la sombra del fondo, o ver bien cual fondo va.

2023-04-14 20:49 UTC, germankern commented
![image](https://user-images.githubusercontent.com/104010145/232152028-db33b894-6d99-4477-b10f-70695b3db13c.png)

2023-04-17 14:57 UTC, adrianponce89 commented
No estan apareciendo los padding internos al menos en la preview en chrome:
![Screen Shot 2023-04-17 at 11 56 19](https://user-images.githubusercontent.com/16446864/232524756-249c565c-ef31-4bb2-9900-97c01bc21eb5.png)

2023-04-17 15:04 UTC, adrianponce89 requested changes

2023-04-17 15:57 UTC, germankern commented
![image](https://user-images.githubusercontent.com/104010145/232542505-447eb31c-8837-449f-b649-0338be3a1a76.png)

con este background: background-color: $color-bg-dark-blue; 
ahora sí esta bastante parecido, me preocupaba eso...

2023-04-17 16:09 UTC, adrianponce89 approved these changes

2023-04-17 16:09 UTC, adrianponce89 commented on src/pages/our-services/index.scss
> +        padding: $margin-md $margin-lg;
proba con 
```
padding: $margin-md;
```

Porque por alguna razón pone: `padding: auto 2rem;` en la preview y hace que no funcione

2023-04-17 16:21 UTC, merged